# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74ea2bbf19ffa6c127f74c2f6da781953df96fdee23f6cd2c5282f9ad08ef407954565ac6bdc9a7f607d846e6c4766379f184ff963114f4bc6a23acfab38afd3

test:
  secret_key_base: 09730c044d2c60c09c6bd317a3af79f19a9b4288e2bc6fdc95f56f70da5700248d7fe0ad90233541db2609d2f563005a7fba4bb6ef229766cb4504941f28b03c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
